name: "[CI] Continuous Integration"

on:
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: 0 0 */5 * *

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_PUBLIC_KEY: ${{ secrets.SUPABASE_PUBLIC_KEY }}
  SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Debug
        run: |
          ls -la
          echo "debug command example"
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome107
      options: --user 1001
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Test - Cypress
        run: npm run test
      - name: Upload test recordings
        uses: actions/upload-artifact@v2
        with:
          name: cypress-test-recordings
          path: cypress/videos
          expire-in: 7d
